name: Linter

on:
  pull_request:
    types: [opened, edited, reopened]
  push:

jobs:
  lint_python:
    name: Python Linter Job
    runs-on: ubuntu-20.04
    continue-on-error: true
    strategy:
      matrix:
        container: [backend, telegram_bot, tests]
    steps:
      - name: Get repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pep8-naming
      - name: Lint (flake8)
        run: |
          flake8 ${{ matrix.container }} --count --max-line-length=120 --max-complexity=10
   
  lint_frontend:
    name: JS/TS Linter Job
    runs-on: ubuntu-20.04
    continue-on-error: true
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 21
      
      - name: Install dependencies
        run: |
          cd frontend/app
          npm ci

      - name: Run code style check
        run: |
          cd frontend/app
          npm run lint
