name: Linter

on:
  pull_request:
    types: [opened, edited, reopened]
  push:

jobs:
  lint_python:
    name: Linter Job
    runs-on: ubuntu-20.04
    continue-on-error: true
    strategy:
      matrix:
        container: [backend, telegram_bot]
    steps:
      - name: Get repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pep8-naming
      - name: Lint (flake8)
        run: |
          flake8 ${{ matrix.container }} --count --max-line-length=120 --max-complexity=10
        
